---
     # deployment setup    
    nsVersion: ns-allinone-3.29
    nsCodeFolder: ns-3.29
    extension: .tar.bz2
    deployFolder: /home/dockemu/src/dockemu
    optimized: false
    # ANTON cambia isto kona! 
    #confFile: /home/dockemu/src/dockemu/NS3DockerEmulator/conf

      # experiment configuration
      # base container name should not contain non-alfanumeric chars 
      # max 8 chars 
    baseContainerName: coapcont
    experimentName: coap-experiment
    logsDirectory: /var/dockemu/logs/
    numberOfClientNodes: 5
    numberOfServerNodes: 1
    serverNode: True
    emulationTime: 3000
    ns3NetworkScript: tap-csma-virtual-machine-client-server
    nodeSpeed: 5
    nodePause: 1
    ns3NetworkParameteres: --ns3::CsmaChannel::DataRate=100000000 

    
      # emulation parameters  
    startns3: False
    ns3Jobs: 1
