---
- name: Install Dockemu dependencies and required packages
  hosts: dockemu
  become: true
  tags:
      - install
  roles:
      - installation

- name: Prepare Docker containers and set ns-3 configuration
  hosts: dockemu
  become: true
  tags:
      - prepare
  roles:
      - preparation
     
- name: Execute Dockemu simulation
  hosts: dockemu
  become: true
  tags:
     - execute
  roles:
      - execution

- name: Cleanup Dockemu simulation
  hosts: dockemu
  become: true
  tags:
     - cleanup
  roles:
      - cleanup
     